# Generated by Django 5.2.1 on 2025-05-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_contact', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=100)),
                ('shipment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('reorder_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Transfer', 'Transfer'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_order', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from', to='rf_dispatch.storagelocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to', to='rf_dispatch.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_shipped', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.outboundorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='InboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.inboundorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.warehouse'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.storagelocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse', 'storage_location')},
            },
        ),
    ]
