# Generated by Django 5.2.1 on 2025-05-26 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_door', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.outboundorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandlingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hu_code', models.CharField(max_length=50, unique=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('outbound_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.outboundorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rf_dispatch.product')),
            ],
        ),
    ]
