# Generated by Django 5.2.1 on 2025-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0002_dispatchsession_handlingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchsession',
            name='dock_door',
            field=models.CharField(max_length=50),
        ),
    ]
