# Generated by Django 5.2.1 on 2025-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_dispatch', '0003_alter_dispatchsession_dock_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
